apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: rlbotstorage
  name: rlbotstorage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
status: {}
